name: Android Build

on:
  pull_request:
    branches:
      - develop
      - beta

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          sdk-version: 34
          build-tools-version: 34.0.0

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

  lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Decode and save the keystore file
        env:
          STORE_FILE_BASE64: ${{ secrets.STORE_FILE_BASE64 }}
        run: |
          echo "$STORE_FILE_BASE64" | base64 --decode > app/keystore.jks

      - name: Load keystore properties
        run: |
          echo "storeFile=keystore.jks" >> app/keystore.properties
          echo "$STORE_FILE_BASE64" | base64 --decode > app/keystore.jks
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> app/keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> app/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> app/keystore.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          sdk-version: 34
          build-tools-version: 34.0.0

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: lint-results-debug.html
          path: app/build/reports/lint-results-debug.html

  package:
    name: Generate Android App Bundle
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Decode and save the keystore file
        env:
          STORE_FILE_BASE64: ${{ secrets.STORE_FILE_BASE64 }}
        run: |
          echo "$STORE_FILE_BASE64" | base64 --decode > app/keystore.jks

      - name: Load keystore properties
        run: |
          echo "storeFile=keystore.jks" >> app/keystore.properties
          echo "$STORE_FILE_BASE64" | base64 --decode > app/keystore.jks
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> app/keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> app/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> app/keystore.properties

      - name: Build Android App Bundle
        run: ./gradlew bundle
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Clean up
        run: rm app/keystore.jks